name: 🚀 Deploy Laravel + React Starter to Hostinger via FTP

on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    name: 📂 Upload to FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠️ Install Dependencies & Build React (Vite)
        run: |
          npm install
          npm run build

      - name: 📂 Deploy Public Folder via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}
          local-dir: ./public
